theme: jekyll-theme-architect

# Site settings
title: Nianlin Zhang
email: zhang.nagle@gmail.com
description: "Devops, Try to be a Hacker"
logo: images/nagle.jpg
url: "https://nagle.dev"
github_repo: "https://github.com/zhangnianlin/zhangnianlin.github.io"

# Sidebar settings
sidebar: true  
sidebar-about-description: "A Devops, Try to be a Hacker"
sidebar-avatar: /images/nagle.jpg
